# Read the documentation: https://symfony.com/doc/master/bundles/FOSRestBundle/index.html
fos_rest:
    param_fetcher_listener:  true
#    allowed_methods_listener:  true
#    routing_loader: true
#    view:
#        view_response_listener:  true
    body_listener:
        enabled: true
        default_format: json
    body_converter:
        enabled: true
        validate: true
        validation_errors_argument: validationErrors
    exception:
        enabled: true
        messages:
            'Symfony\Component\Validator\Exception\ValidatorException': true
        codes:
            'Symfony\Component\Validator\Exception\ValidatorException': 400
    routing_loader:
        default_format: json
        include_format: false
    format_listener:
        enabled: true
        rules:
            - { path: "^/api", prefer_extension: true, fallback_format: json, priorities: [ json, html ] }
